# #Swagger Petstore
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: 1.0.0
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 6.2.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Addlprops::ShowPetById200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Addlprops::ShowPetById200Response do

  describe "test an instance of ShowPetById200Response" do
    it "should create an instance of ShowPetById200Response" do
      #instance = Addlprops::ShowPetById200Response.new
      #expect(instance).to be_instance_of(Addlprops::ShowPetById200Response)
    end
  end
  describe "test attribute 'id'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'name'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'info'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
